import numpy as np
from prtp.Rays import Rays

class Source:
    '''
    class Source:
    This class is what is initially passed to an Instrument object. This class
        contains information about how to generate a Rays object for use in
        an instrument
    '''
    
    def __init__(self, num = 0, wave = None, order = None):
        '''
        Function __init__:
        
        Inputs:
        num - The number of photons you want to generate
        wave - The wavelength of the photons. Can be a float or an array that
            has length num
        order - The order of the photons. Can be an integer or an array that
            has length num
        '''
        self.type = type
        self.num = num
        self.wave = wave
        self.order = order
        self.rays = None
    
    def addMisalignment(self, dx = 0,dy = 0, dz = 0, dl = 0, dm = 0, dn = 0):
        '''
        Function addMisalignment:
        Initializes misalingments of the Rays
        
        Inputs:
        dx,dy,... - Give the amount that the rays should be transformed in each
            direction
        
        Outputs:
        None
        '''
        self.dx = dx
        self.dy = dy
        self.dz = dz
        self.dl = dl
        self.dm = dm
        self.dn = dn
    
    def misalign(self,rays):
        '''
        Function Misalign:
        Executes the transformation to misalign the rays
        
        Inputs:
        rays - The rays to be misaligned
        
        Outputs:
        Nothing
        
        Notes:
        - This function uses a try-except block to see if the misalignment 
            values have been specified (if they have not bee initialized, trying
            to access them will yield an error, which means we don't have to
            misalign the rays at all.) But this method makes it difficult to
            determine if a different error is occurring here, consider changing
            how this function works
        '''
        try:
            # Add misalignments if they've been defined
            rays.transform(self.dx,self.dy,self.dz,self.dl,self.dm,self.dn)
        except:
            # This executes if misalignments have not been defined
            pass
    
    def addParams(self,rays):
        '''
        Function addParams:
        Adds the Wavelength and Order Parameters to the Rays object
        
        Inputs:
        rays - The Rays object you want to add Params to
        
        Outputs:
        None
        
        Notes:
        - If no parameters have been defined, errors will be caused down the line
            and it may be difficult to recognize them. But I also want the user
            to be able to define a Source without waves and orders. Think about
            adding a warning to the user that no waves or orders have been 
            added
        '''
        if (self.wave is not None):
            if type(self.wave) == np.ndarray:
                rays.addParam('Wavelength',self.wave)
            else:
                rays.addParam('Wavelength',np.array([self.wave]*len(rays)))
        if (self.order is not None):
            if type(self.wave) == np.ndarray:
                rays.addParam('Order',self.order)
            else:
                rays.addParam('Order',np.array([self.order]*len(rays)))
    
    def getRays():
        '''
        Function getRays:
        Returns the Rays that have been generated by generateRays()
        '''
        if self.rays is None:
            self.generateRays()
        return self.rays